apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: eks-argocd  
  labels:
    name: apps
  finalizers:
    # Ensures resources (Pods, Services, etc.) are deleted first before the Application itself
    - argocd.argoproj.io/resources-finalizer # '/' is used as per Kubernetes best practices
spec:
  project: default 
  source:
    repoURL: https://github.com/YD-git428/EKS-project/terraform.git
    targetRevision: HEAD  
    path: apps 
  destination:
    server: https://kubernetes.default.svc
    namespace: apps 
  syncPolicy:
    automated:
      #Anything deleted in the source (Github repo) will be considered unnecessary thus deleted in the destination (kubernetes cluster) to remain in sync 
      prune: true 
      #Any modifications in the cluster will return back to original state as defined in the source (Github repo)
      selfHeal: true 
      #Ensures no deletions are made in the cluster in the period that its empty within the GitHub Repository = no downtime
      allowEmpty: false 
    syncOptions:    
      - CreateNamespace=true  
