apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: remindersofspokenword@gmail.com
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z02736193B0NBZU8BTQQK
          region: eu-west-2
      selector:
        dnsZones: 
        - "youcefderder.co.uk"
    - http01:
        ingress:
          class: nginx
       
         
