apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $EMAIL #Insert your email
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: $HOSTEDZONE_ID #Insert your Hosted Zone ID
          region: $REGION #Insert your region
      selector:
        dnsZones: 
        - "youcefderder.co.uk" #Insert your domain
    - http01:
        ingress:
          class: nginx
       
         
