name: Deploy EKS Infrastructure + Install Helm
on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm apply'
          required: true
          default: 'no'



jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure-AWS-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v4
      with:
          version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
          version: 'latest'


    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt --recursive

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -refresh=true -input=false
      continue-on-error: false

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve -input=false