name: Destroy deployed infrastructure
on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm cleanup'
          required: true
          default: 'no'

jobs:
 tf-destroy:
   runs-on: ubuntu-latest

   steps:
     - name: Check out repository
       uses: actions/checkout@v3

     - name: Configure-AWS-credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

     - name: Update kube config
       run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name YoucefEKS-project
       continue-on-error: true
       
     - name: Uninstall all CRDs
       run: |
         chmod +x cleanup.sh
         sh cleanup.sh
       continue-on-error: true

     - name: Terraform Init
       run: |
           pwd
           cd terraform
           terraform init

     - name: Terraform Plan
       run: |
         cd terraform
         terraform plan -refresh=true -input=false
       continue-on-error: false

     - name: Terraform destroy
       run: |
         cd terraform
         terraform destroy -auto-approve