name: Destroy deployed infrastructure
on:
    workflow_dispatch:
      inputs:
        confirmation:
          description: 'Type "yes" to confirm cleanup'
          required: true
          default: 'no'

jobs:
 tf-destroy:
   runs-on: ubuntu-latest

   steps:
     - name: Check out repository
       uses: actions/checkout@v3

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Configure-AWS-credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

     - name: Allow GitHub Actions IP in EKS
       run: |
             GITHUB_IP=$(curl -s https://checkip.amazonaws.com)
             aws eks update-cluster-config --region ${{ secrets.AWS_REGION }} --name YoucefEKS-project \
             --resources-vpc-config endpointPublicAccess=true,publicAccessCidrs=["$GITHUB_IP/32",${{ secrets.PUBLIC_IP_CIDR }}]

     - name: Update kube config
       run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name YoucefEKS-project
       continue-on-error: true

     - name: Uninstall all CRDs
       run: |
         chmod +x cleanup.sh
         sh cleanup.sh
       continue-on-error: true

     - name: Terraform Init
       working-directory: terraform
       run: |
           terraform init

     - name: Terraform Plan
       working-directory: terraform
       run: |
         terraform plan -refresh=true -input=false
       continue-on-error: false

     - name: Terraform destroy
       working-directory: terraform
       run: |
         terraform destroy -auto-approve